- name: Install PHP 7.4 from Remi repository
  yum:
    name: php
    state: present
  when: ansible_distribution_major_version == "7"
  tags:
    - php

- name: Enable Remi repository for PHP 7.4
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
  when: ansible_distribution_major_version == "7"
  tags:
    - remi

- name: Enable PHP 7.4 in Remi repository
  yum_repository:
    name: remi-php74
    description: Remi's PHP 7.4 RPM repository for Enterprise Linux 7 - $basearch
    baseurl: https://rpms.remirepo.net/enterprise/7/php74/$basearch/
    gpgcheck: yes
    gpgkey: https://rpms.remirepo.net/RPM-GPG-KEY-remi
    enabled: yes
