- name: Extract Wordpress
  unarchive:
    src: /tmp/latest.tar.gz
    dest: /var/www/html/
    remote_src: yes
    extra_opts: [--strip-components=1]
  notify:
    - Restart Apache
  tags:
    - wordpress

- name: Set ownership of Wordpress files
  file:
    path: /var/www/html/
    owner: apache
    group: apache
    recurse: yes
