- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - httpd
    - wget
    - unzip
    - epel-release
    - mysql
    - mariadb
    - mariadb-server
  when: ansible_distribution_major_version == "7"
