- name: Create MySQL database for WordPress
  hosts: all
  become: true
  tasks:
    - name: Creating WordPress database
      shell:
        cmd: mysql -u root -e "CREATE DATABASE IF NOT EXISTS wordpress;"

- name: Create MySQL user for WordPress
  hosts: all
  become: true
  tasks:
    - name: Creating WordPress database user
      shell:
        cmd: mysql -u root -e "CREATE USER 'nursulu97'@'localhost' IDENTIFIED BY 'kaizen123'; GRANT ALL PRIVILEGES ON wordpress.* TO 'wordpressuser'@'localhost'; FLUSH PRIVILEGES;"
